
@api = http://localhost:3000/users
GET {{api}}

####
GET {{api}}/3
#####
GET {{api}}/count
###
POST {{api}}
Content-Type: application/json

{
    "name": "Vicky",
    "lastname": "Rivero",
    "address": "Ave Sandino",
    "email": "vrivero@gmail.com"

}
###
DELETE {{api}}/2